<?php

namespace Database\Seeders;

use App\Models\Hotel;
use App\Models\User;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class HotelSeeder extends Seeder
{
    public function run(): void
    {
        Hotel::query()->delete();

        $hotels = [
            // =========================================================================
            // 1. ELLA & HIGHLAND CLUSTER (Nine Arches, Little Adam's, Ella Rock, Ravana)
            // =========================================================================
            [
                'owner_name' => 'Gamini Wickramasinghe',
                'owner_email' => 'gamini.wickramasinghe@example.com',
                'hotel_name' => '98 Acres Resort & Spa',
                'description' => 'A luxury boutique eco-resort perched on a scenic 98-acre tea estate in Ella, offering panoramic views of Ella Gap and Little Adam\'s Peak. Designed with natural straw-thatched stone chalets.',
                'address' => 'Passara Road, Ella',
                'contact_number' => '+94572050050',
                'whatsapp_number' => '+94771234501',
                'email' => 'info@resort98acres.com',
                'budget_tier' => 'luxury',
                'pricing_model' => 'per_room',
                'base_price' => 85000.00,
                'max_total_capacity' => 60,
                'is_wheelchair_accessible' => true,
                'latitude' => 6.8660,
                'longitude' => 81.0573,
            ],
            [
                'owner_name' => 'Rohana Bandara',
                'owner_email' => 'rohana.bandara@example.com',
                'hotel_name' => 'Country Homes Ella',
                'description' => 'Charming mid-range wooden chalets nestled in nature with direct mountain views of Ella Rock, warm hospitality, and home-cooked traditional meals.',
                'address' => 'Wellawaya Road, Ella',
                'contact_number' => '+94572228500',
                'whatsapp_number' => '+94714567802',
                'email' => 'stay@countryhomesella.com',
                'budget_tier' => 'mid_range',
                'pricing_model' => 'per_room',
                'base_price' => 22000.00,
                'max_total_capacity' => 30,
                'is_wheelchair_accessible' => false,
                'latitude' => 6.8680,
                'longitude' => 81.0490,
            ],
            [
                'owner_name' => 'Nuwan Jayawardena',
                'owner_email' => 'nuwan.jayawardena@example.com',
                'hotel_name' => 'Ella Mount View Guest House',
                'description' => 'Budget-friendly guesthouse popular among solo hikers, backpackers, and digital nomads. Close proximity to railway station and trailheads.',
                'address' => 'Station Road, Ella',
                'contact_number' => '+94773456789',
                'whatsapp_number' => '+94773456789',
                'email' => 'ellamountview@gmail.com',
                'budget_tier' => 'budget',
                'pricing_model' => 'per_room',
                'base_price' => 6500.00,
                'max_total_capacity' => 14,
                'is_wheelchair_accessible' => false,
                'latitude' => 6.8725,
                'longitude' => 81.0475,
            ],
            [
                'owner_name' => 'Chaminda Silva',
                'owner_email' => 'chaminda.silva@example.com',
                'hotel_name' => 'Ella Flower Garden Resort',
                'description' => 'Surrounded by manicured flower beds and tea plants, offering comfortable rooms with private balconies facing the waterfalls and Ella valley.',
                'address' => '3rd Mile Post, Passara Road, Ella',
                'contact_number' => '+94572228800',
                'whatsapp_number' => '+94762345601',
                'email' => 'reservations@ellaflowergarden.com',
                'budget_tier' => 'mid_range',
                'pricing_model' => 'per_room',
                'base_price' => 18500.00,
                'max_total_capacity' => 45,
                'is_wheelchair_accessible' => true,
                'latitude' => 6.8710,
                'longitude' => 81.0540,
            ],

            // =========================================================================
            // 2. SOUTHERN COAST (Mirissa, Coconut Tree Hill, Unawatuna, Galle Fort)
            // =========================================================================
            [
                'owner_name' => 'Sunil De Silva',
                'owner_email' => 'sunil.desilva@example.com',
                'hotel_name' => 'Weligama Bay Marriott Resort & Spa',
                'description' => '5-star beachfront luxury property situated along Weligama Bay just minutes from Mirissa. Modern suites with panoramic ocean views, infinity pools, and rooftop lounge.',
                'address' => '700 Matara Road, Pelena, Weligama',
                'contact_number' => '+94414600100',
                'whatsapp_number' => '+94777890101',
                'email' => 'mhrs.weligama@marriott.com',
                'budget_tier' => 'luxury',
                'pricing_model' => 'per_room',
                'base_price' => 95000.00,
                'max_total_capacity' => 200,
                'is_wheelchair_accessible' => true,
                'latitude' => 5.9723,
                'longitude' => 80.4289,
            ],
            [
                'owner_name' => 'Asela Gunaratne',
                'owner_email' => 'asela.gunaratne@example.com',
                'hotel_name' => 'Paradise Beach Club Mirissa',
                'description' => 'Prime beachfront resort situated directly on Mirissa Beach. Features beach access, outdoor swimming pool, diving school, and whale-watching booking desk.',
                'address' => 'Giritara, Mirissa',
                'contact_number' => '+94412259980',
                'whatsapp_number' => '+94715678903',
                'email' => 'info@paradisebeachmirissa.com',
                'budget_tier' => 'mid_range',
                'pricing_model' => 'per_room',
                'base_price' => 26000.00,
                'max_total_capacity' => 70,
                'is_wheelchair_accessible' => true,
                'latitude' => 5.9455,
                'longitude' => 80.4550,
            ],
            [
                'owner_name' => 'Kasun Dissanayake',
                'owner_email' => 'kasun.dissanayake@example.com',
                'hotel_name' => 'Hangover Hostels Mirissa',
                'description' => 'Top-rated social backpacker hostel located a short walk from Mirissa Beach and Coconut Tree Hill. Air-conditioned bunk rooms and shared social common spaces.',
                'address' => 'Main Street, Bandaramulla, Mirissa',
                'contact_number' => '+94771239876',
                'whatsapp_number' => '+94771239876',
                'email' => 'mirissa@hangoverhostels.com',
                'budget_tier' => 'budget',
                'pricing_model' => 'per_person',
                'base_price' => 4500.00,
                'max_total_capacity' => 40,
                'is_wheelchair_accessible' => false,
                'latitude' => 5.9488,
                'longitude' => 80.4610,
            ],
            [
                'owner_name' => 'Mahesh Perera',
                'owner_email' => 'mahesh.perera@example.com',
                'hotel_name' => 'Amangalla Resort Galle Fort',
                'description' => 'Historic ultra-luxury heritage hotel located within the ramparts of UNESCO Galle Dutch Fort. Combines 400-year-old colonial grandeur with world-class wellness.',
                'address' => '10 Church Street, Galle Fort, Galle',
                'contact_number' => '+94912233388',
                'whatsapp_number' => '+94773344556',
                'email' => 'amangalla@aman.com',
                'budget_tier' => 'luxury',
                'pricing_model' => 'per_room',
                'base_price' => 140000.00,
                'max_total_capacity' => 45,
                'is_wheelchair_accessible' => true,
                'latitude' => 6.0275,
                'longitude' => 80.2173,
            ],
            [
                'owner_name' => 'Suraj Mendis',
                'owner_email' => 'suraj.mendis@example.com',
                'hotel_name' => 'Calamander Unawatuna Beach Resort',
                'description' => 'Vibrant beachfront resort on the crescent of Unawatuna Bay. Perfect for families and couples seeking watersports, swimming, and beachside dining.',
                'address' => 'Devala Road, Unawatuna',
                'contact_number' => '+94912224900',
                'whatsapp_number' => '+94768899001',
                'email' => 'reservations@calamanderbeach.com',
                'budget_tier' => 'mid_range',
                'pricing_model' => 'per_room',
                'base_price' => 28000.00,
                'max_total_capacity' => 90,
                'is_wheelchair_accessible' => true,
                'latitude' => 6.0118,
                'longitude' => 80.2475,
            ],

            // =========================================================================
            // 3. YALA WILDLIFE ZONE
            // =========================================================================
            [
                'owner_name' => 'Dharshan Munidasa',
                'owner_email' => 'dharshan.munidasa@example.com',
                'hotel_name' => 'Cinnamon Wild Yala',
                'description' => 'Luxury wilderness lodge located on the border of Yala National Park, where elephants and wildlife roam freely between chalets and the observation deck.',
                'address' => 'Kirinda, Palatupana, Yala',
                'contact_number' => '+94472239449',
                'whatsapp_number' => '+94772233445',
                'email' => 'wild@cinnamonhotels.com',
                'budget_tier' => 'luxury',
                'pricing_model' => 'per_room',
                'base_price' => 75000.00,
                'max_total_capacity' => 80,
                'is_wheelchair_accessible' => true,
                'latitude' => 6.2842,
                'longitude' => 81.4055,
            ],
            [
                'owner_name' => 'Nalin Jayasuriya',
                'owner_email' => 'nalin.jayasuriya@example.com',
                'hotel_name' => 'Hotel Chandrika Tissamaharama',
                'description' => 'Comfortable mid-tier safari base camp hotel located in Tissamaharama, convenient for morning and evening game drives into Yala National Park.',
                'address' => 'Kataragama Road, Tissamaharama',
                'contact_number' => '+94472237264',
                'whatsapp_number' => '+94718877665',
                'email' => 'chandrika@taruvillas.com',
                'budget_tier' => 'mid_range',
                'pricing_model' => 'per_room',
                'base_price' => 20000.00,
                'max_total_capacity' => 50,
                'is_wheelchair_accessible' => true,
                'latitude' => 6.2820,
                'longitude' => 81.2910,
            ],
            [
                'owner_name' => 'Samantha Rathnayake',
                'owner_email' => 'samantha.rathnayake@example.com',
                'hotel_name' => 'Yala Leopard Eco Camps',
                'description' => 'Rustic canvas safari camp offering guided game drives, night campfires, and authentic Sri Lankan bush dining for wildlife enthusiasts.',
                'address' => 'Palatupana Junction, Yala Road',
                'contact_number' => '+94776655443',
                'whatsapp_number' => '+94776655443',
                'email' => 'info@yalaecocamps.com',
                'budget_tier' => 'budget',
                'pricing_model' => 'per_person',
                'base_price' => 9500.00,
                'max_total_capacity' => 20,
                'is_wheelchair_accessible' => false,
                'latitude' => 6.2950,
                'longitude' => 81.3850,
            ],

            // =========================================================================
            // 4. CULTURAL TRIANGLE (Sigiriya, Pidurangala, Dambulla, Minneriya)
            // =========================================================================
            [
                'owner_name' => 'Ranjith Fernando',
                'owner_email' => 'ranjith.fernando@example.com',
                'hotel_name' => 'Heritance Kandalama',
                'description' => 'Geoffrey Bawa architectural masterpiece built into a cliff overlooking Kandalama Lake and Sigiriya Rock Fortress. World-renowned 5-star eco-resort.',
                'address' => 'PO Box 11, Dambulla',
                'contact_number' => '+94665555000',
                'whatsapp_number' => '+94779900112',
                'email' => 'kandalama@heritancehotels.com',
                'budget_tier' => 'luxury',
                'pricing_model' => 'per_room',
                'base_price' => 78000.00,
                'max_total_capacity' => 180,
                'is_wheelchair_accessible' => true,
                'latitude' => 7.8687,
                'longitude' => 80.7183,
            ],
            [
                'owner_name' => 'Lalith Senanayake',
                'owner_email' => 'lalith.senanayake@example.com',
                'hotel_name' => 'Hotel Sigiriya',
                'description' => 'Eco-friendly hotel featuring an iconic swimming pool with direct, unobstructed views of Sigiriya Lion Rock rising out of the tree canopy.',
                'address' => 'Hotel Road, Sigiriya',
                'contact_number' => '+94662286821',
                'whatsapp_number' => '+94774433221',
                'email' => 'res.sigiriya@brownshotels.com',
                'budget_tier' => 'mid_range',
                'pricing_model' => 'per_room',
                'base_price' => 27000.00,
                'max_total_capacity' => 90,
                'is_wheelchair_accessible' => true,
                'latitude' => 7.9540,
                'longitude' => 80.7520,
            ],
            [
                'owner_name' => 'Anura Kumara',
                'owner_email' => 'anura.kumara@example.com',
                'hotel_name' => 'Sigiriya Jungle Homestay & Treehouse',
                'description' => 'Authentic village homestay featuring treehouse rooms with views of Pidurangala Rock, organic home-grown meals, and cycle rental services.',
                'address' => 'Inamaluwa Road, Sigiriya',
                'contact_number' => '+94719988776',
                'whatsapp_number' => '+94719988776',
                'email' => 'sigiriyahomestay@gmail.com',
                'budget_tier' => 'budget',
                'pricing_model' => 'per_room',
                'base_price' => 5800.00,
                'max_total_capacity' => 12,
                'is_wheelchair_accessible' => false,
                'latitude' => 7.9610,
                'longitude' => 80.7480,
            ],
            [
                'owner_name' => 'Chitral Jayatilake',
                'owner_email' => 'chitral.jayatilake@example.com',
                'hotel_name' => 'Cinnamon Lodge Habarana',
                'description' => 'Sprawling 5-star lakeside sanctuary located between Minneriya National Park and Sigiriya. Prime hub for elephant safari excursions.',
                'address' => 'PO Box 02, Habarana',
                'contact_number' => '+94662270011',
                'whatsapp_number' => '+94771122334',
                'email' => 'lodge@cinnamonhotels.com',
                'budget_tier' => 'luxury',
                'pricing_model' => 'per_room',
                'base_price' => 62000.00,
                'max_total_capacity' => 120,
                'is_wheelchair_accessible' => true,
                'latitude' => 8.0315,
                'longitude' => 80.7510,
            ],

            // =========================================================================
            // 5. ANURADHAPURA & POLONNARUWA (Ancient Kingdoms)
            // =========================================================================
            [
                'owner_name' => 'Ravi Karunanayake',
                'owner_email' => 'ravi.karunanayake@example.com',
                'hotel_name' => 'The Heritage Hotel Anuradhapura',
                'description' => 'Colonial-style mid-tier hotel surrounded by ancient reservoirs and paddy fields, close to the Sacred Bo Tree and Ruwanwelisaya.',
                'address' => 'Potanegama, Anuradhapura',
                'contact_number' => '+94252223900',
                'whatsapp_number' => '+94775566778',
                'email' => 'info@theheritagehotel.lk',
                'budget_tier' => 'mid_range',
                'pricing_model' => 'per_room',
                'base_price' => 19000.00,
                'max_total_capacity' => 55,
                'is_wheelchair_accessible' => true,
                'latitude' => 8.3280,
                'longitude' => 80.3890,
            ],
            [
                'owner_name' => 'Dammika Weerasinghe',
                'owner_email' => 'dammika.weerasinghe@example.com',
                'hotel_name' => 'The Lake House Polonnaruwa',
                'description' => 'Historic boutique hotel situated on the banks of Parakrama Samudra, offering refined tranquility and views of ancient water ruins.',
                'address' => 'Lake Road, Polonnaruwa',
                'contact_number' => '+94272222212',
                'whatsapp_number' => '+94763322114',
                'email' => 'reservations@thelakehouse.lk',
                'budget_tier' => 'luxury',
                'pricing_model' => 'per_room',
                'base_price' => 52000.00,
                'max_total_capacity' => 40,
                'is_wheelchair_accessible' => true,
                'latitude' => 7.9350,
                'longitude' => 81.0020,
            ],

            // =========================================================================
            // 6. KANDY & KNUCKLES / MEEMURE HUB
            // =========================================================================
            [
                'owner_name' => 'Hiran Cooray',
                'owner_email' => 'hiran.cooray@example.com',
                'hotel_name' => 'Earl\'s Regency Hotel Kandy',
                'description' => '5-star luxury hillside hotel overlooking the Mahaweli River, minutes away from the Temple of the Sacred Tooth Relic.',
                'address' => 'Tennekumbura, Kandy',
                'contact_number' => '+94812422122',
                'whatsapp_number' => '+94773322110',
                'email' => 'earls@aitkenspence.lk',
                'budget_tier' => 'luxury',
                'pricing_model' => 'per_room',
                'base_price' => 58000.00,
                'max_total_capacity' => 150,
                'is_wheelchair_accessible' => true,
                'latitude' => 7.2917,
                'longitude' => 80.6698,
            ],
            [
                'owner_name' => 'Tissa Premasiri',
                'owner_email' => 'tissa.premasiri@example.com',
                'hotel_name' => 'Madulkelle Tea and Eco Lodge',
                'description' => 'Luxury tented lodges overlooking the Knuckles Mountain Range. Gateway for hikers heading toward Meemure and mountain peaks.',
                'address' => 'Madulkelle, Kandy',
                'contact_number' => '+94815670500',
                'whatsapp_number' => '+94779876543',
                'email' => 'info@madulkelle.com',
                'budget_tier' => 'luxury',
                'pricing_model' => 'per_room',
                'base_price' => 89000.00,
                'max_total_capacity' => 35,
                'is_wheelchair_accessible' => false,
                'latitude' => 7.3942,
                'longitude' => 80.7061,
            ],
            [
                'owner_name' => 'Kalu Bandara',
                'owner_email' => 'kalu.bandara@example.com',
                'hotel_name' => 'Meemure Riverside Eco Camps',
                'description' => 'Rustic wooden huts and riverside camping setups in Meemure deep wilderness. Includes authentic village cuisine and natural pool bathing.',
                'address' => 'Meemure Village, Knuckles Range',
                'contact_number' => '+94712349988',
                'whatsapp_number' => '+94712349988',
                'email' => 'staymeemure@gmail.com',
                'budget_tier' => 'budget',
                'pricing_model' => 'per_person',
                'base_price' => 5500.00,
                'max_total_capacity' => 25,
                'is_wheelchair_accessible' => false,
                'latitude' => 7.4328,
                'longitude' => 80.8465,
            ],

            // =========================================================================
            // 7. NUWARA ELIYA, HAPUTALE & HIGHLANDS (Lipton's Seat, Adisham, Horton Plains)
            // =========================================================================
            [
                'owner_name' => 'Victor Senaratne',
                'owner_email' => 'victor.senaratne@example.com',
                'hotel_name' => 'The Grand Hotel Nuwara Eliya',
                'description' => 'Exquisite Elizabethan-era heritage hotel surrounded by award-winning manicured gardens and cool highland mountain mists.',
                'address' => 'Grand Hotel Road, Nuwara Eliya',
                'contact_number' => '+94522222881',
                'whatsapp_number' => '+94778899112',
                'email' => 'grand@tangerinehotels.com',
                'budget_tier' => 'luxury',
                'pricing_model' => 'per_room',
                'base_price' => 72000.00,
                'max_total_capacity' => 160,
                'is_wheelchair_accessible' => true,
                'latitude' => 6.9698,
                'longitude' => 80.7675,
            ],
            [
                'owner_name' => 'Suneth Weerakkody',
                'owner_email' => 'suneth.weerakkody@example.com',
                'hotel_name' => 'Melheim Resort & Spa Haputale',
                'description' => 'Boutique mountain retreat set on the southern cliff face of Haputale, near Adisham Bungalow and Lipton\'s Seat trails.',
                'address' => 'Beragala, Haputale',
                'contact_number' => '+94572268400',
                'whatsapp_number' => '+94772299881',
                'email' => 'info@melheimresort.com',
                'budget_tier' => 'mid_range',
                'pricing_model' => 'per_room',
                'base_price' => 32000.00,
                'max_total_capacity' => 35,
                'is_wheelchair_accessible' => true,
                'latitude' => 6.7720,
                'longitude' => 80.9380,
            ],

            // =========================================================================
            // 8. EAST COAST (Arugam Bay & Nilaveli Beach)
            // =========================================================================
            [
                'owner_name' => 'Mohamed Riyas',
                'owner_email' => 'mohamed.riyas@example.com',
                'hotel_name' => 'Jetwing Surf Arugam Bay',
                'description' => 'Eco-luxury surf retreat of woven seashell chalets on the secluded sands of Pottuvil Point, minutes from Arugam Bay point breaks.',
                'address' => 'Pottuvil Point, Arugam Bay',
                'contact_number' => '+94632051100',
                'whatsapp_number' => '+94773355779',
                'email' => 'surf@jetwinghotels.com',
                'budget_tier' => 'luxury',
                'pricing_model' => 'per_room',
                'base_price' => 68000.00,
                'max_total_capacity' => 50,
                'is_wheelchair_accessible' => true,
                'latitude' => 6.8810,
                'longitude' => 81.8480,
            ],
            [
                'owner_name' => 'Farhan Nizam',
                'owner_email' => 'farhan.nizam@example.com',
                'hotel_name' => 'Mambo\'s Arugam Bay Beach Cabanas',
                'description' => 'Iconic beachfront cabanas located directly at the Main Surf Point in Arugam Bay. Surfer paradise with live music and board rentals.',
                'address' => 'Main Surf Point, Arugam Bay',
                'contact_number' => '+94776123456',
                'whatsapp_number' => '+94776123456',
                'email' => 'mambosurf@gmail.com',
                'budget_tier' => 'budget',
                'pricing_model' => 'per_room',
                'base_price' => 8500.00,
                'max_total_capacity' => 28,
                'is_wheelchair_accessible' => false,
                'latitude' => 6.8415,
                'longitude' => 81.8310,
            ],
            [
                'owner_name' => 'Siva Thangarajah',
                'owner_email' => 'siva.thangarajah@example.com',
                'hotel_name' => 'Nilaveli Beach Hotel Trincomalee',
                'description' => 'Classic coastal resort situated directly across from Pigeon Island Marine Park. Crystal waters, soft white sand, and water sports center.',
                'address' => 'Nilaveli, Trincomalee',
                'contact_number' => '+94262232295',
                'whatsapp_number' => '+94778844220',
                'email' => 'res@nilavelibeachhotel.com',
                'budget_tier' => 'mid_range',
                'pricing_model' => 'per_room',
                'base_price' => 24000.00,
                'max_total_capacity' => 85,
                'is_wheelchair_accessible' => true,
                'latitude' => 8.6895,
                'longitude' => 81.1878,
            ],

            // =========================================================================
            // 9. NORTHERN PROVINCE (Jaffna & Nallur)
            // =========================================================================
            [
                'owner_name' => 'Kuganathan Selvam',
                'owner_email' => 'kuganathan.selvam@example.com',
                'hotel_name' => 'Jetwing Jaffna',
                'description' => 'Modern city hotel in the heart of Jaffna town, showcasing Northern Sri Lankan hospitality, cultural cuisine, and proximity to Nallur Kovil.',
                'address' => '37 Mahatma Gandhi Road, Jaffna',
                'contact_number' => '+94212215577',
                'whatsapp_number' => '+94771299883',
                'email' => 'jaffna@jetwinghotels.com',
                'budget_tier' => 'luxury',
                'pricing_model' => 'per_room',
                'base_price' => 45000.00,
                'max_total_capacity' => 110,
                'is_wheelchair_accessible' => true,
                'latitude' => 9.6644,
                'longitude' => 80.0152,
            ],
            [
                'owner_name' => 'Niranjan Pathmanathan',
                'owner_email' => 'niranjan.pathmanathan@example.com',
                'hotel_name' => 'The Valampuri Hotel Jaffna',
                'description' => 'Comfortable mid-range cultural hotel located right next to the Jaffna Railway Station with swimming pool and authentic Jaffna crab curries.',
                'address' => '148/10 Station Road, Jaffna',
                'contact_number' => '+94212030300',
                'whatsapp_number' => '+94765544332',
                'email' => 'info@thevalampuri.com',
                'budget_tier' => 'mid_range',
                'pricing_model' => 'per_room',
                'base_price' => 18000.00,
                'max_total_capacity' => 60,
                'is_wheelchair_accessible' => true,
                'latitude' => 9.6660,
                'longitude' => 80.0210,
            ],

            // =========================================================================
            // 10. RAINFOREST & WILDERNESS (Sinharaja Reserve)
            // =========================================================================
            [
                'owner_name' => 'Rukman De Silva',
                'owner_email' => 'rukman.desilva@example.com',
                'hotel_name' => 'The Rainforest Eco Lodge Sinharaja',
                'description' => 'Award-winning eco-luxury chalets built from recycled shipping containers inside the tea plantation buffer zone of Sinharaja Rainforest.',
                'address' => 'Enselwatte, Deniyaya',
                'contact_number' => '+94114767888',
                'whatsapp_number' => '+94773344118',
                'email' => 'info@rainforestecolodge.com',
                'budget_tier' => 'luxury',
                'pricing_model' => 'per_person',
                'base_price' => 38000.00,
                'max_total_capacity' => 32,
                'is_wheelchair_accessible' => false,
                'latitude' => 6.3810,
                'longitude' => 80.4620,
            ],
            [
                'owner_name' => 'Mahinda Rathnayake',
                'owner_email' => 'mahinda.rathnayake@example.com',
                'hotel_name' => 'Sinharaja Birding & Nature Homestay',
                'description' => 'Budget rustic lodge at the Kudawa gate of Sinharaja, catering to birdwatchers, botanists, and nature lovers seeking expert trail guides.',
                'address' => 'Kudawa, Weddagala, Sinharaja',
                'contact_number' => '+94718822440',
                'whatsapp_number' => '+94718822440',
                'email' => 'sinharajabirding@gmail.com',
                'budget_tier' => 'budget',
                'pricing_model' => 'per_person',
                'base_price' => 5000.00,
                'max_total_capacity' => 16,
                'is_wheelchair_accessible' => false,
                'latitude' => 6.4310,
                'longitude' => 80.4210,
            ],

            // =========================================================================
            // 11. COLOMBO COMMERCIAL CAPITAL
            // =========================================================================
            [
                'owner_name' => 'Sanjiva Senanayake',
                'owner_email' => 'sanjiva.senanayake@example.com',
                'hotel_name' => 'Cinnamon Grand Colombo',
                'description' => 'Iconic 5-star luxury city hotel in the heart of Colombo, offering 14 specialty restaurants, luxury shopping complexes, and premier business amenities.',
                'address' => '77 Galle Road, Colombo 03',
                'contact_number' => '+94112437437',
                'whatsapp_number' => '+94772244668',
                'email' => 'grand@cinnamonhotels.com',
                'budget_tier' => 'luxury',
                'pricing_model' => 'per_room',
                'base_price' => 55000.00,
                'max_total_capacity' => 300,
                'is_wheelchair_accessible' => true,
                'latitude' => 6.9200,
                'longitude' => 79.8480,
            ],
            [
                'owner_name' => 'Pradeep Kaluwitharana',
                'owner_email' => 'pradeep.kaluwitharana@example.com',
                'hotel_name' => 'Cinnamon Red Colombo',
                'description' => 'Modern lean-luxury hotel in central Colombo with a signature infinity rooftop pool and bar overlooking the Indian Ocean.',
                'address' => '59 Ananda Coomaraswamy Mawatha, Colombo 03',
                'contact_number' => '+94112111444',
                'whatsapp_number' => '+94773355991',
                'email' => 'red@cinnamonhotels.com',
                'budget_tier' => 'mid_range',
                'pricing_model' => 'per_room',
                'base_price' => 26000.00,
                'max_total_capacity' => 140,
                'is_wheelchair_accessible' => true,
                'latitude' => 6.9125,
                'longitude' => 79.8550,
            ]
        ];

        foreach ($hotels as $data) {
            // 1. Create or retrieve vendor user account
            $owner = User::updateOrCreate(
                ['email' => $data['owner_email']],
                [
                    'name' => $data['owner_name'],
                    'password' => Hash::make('password123'),
                    'role' => 'hotel_owner',
                    'email_verified_at' => now(),
                ]
            );

            $lat = $data['latitude'];
            $lng = $data['longitude'];

            unset($data['owner_name'], $data['owner_email'], $data['latitude'], $data['longitude']);

            // 2. Insert Hotel with PostGIS geography coordinates
            $hotel = new Hotel($data);
            $hotel->user_id = $owner->id;
            $hotel->coordinates = DB::raw("ST_SetSRID(ST_MakePoint({$lng}, {$lat}), 4326)::geography");
            $hotel->save();
        }
    }
}