<?php

namespace Database\Seeders;

use App\Models\User;
use App\Models\Vehicle;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class VehicleSeeder extends Seeder
{
    public function run(): void
    {
        Vehicle::query()->delete();

        $vehicles = [
            // =========================================================================
            // 1. YALA & SAFARI HUBS (4x4 Off-Road Safari Jeeps & Heavy SUVs)
            // =========================================================================
            [
                'owner_name' => 'Roshan Jayathilake',
                'owner_email' => 'roshan.jayathilake@example.com',
                'vehicle_make_model' => 'Toyota Land Cruiser 70 Series Safari Modified',
                'registration_number' => 'SP CP-4512',
                'rental_type' => 'with_driver',
                'driver_name' => 'Roshan Jayathilake',
                'contact_number' => '+94772112233',
                'whatsapp_number' => '+94772112233',
                'vehicle_type' => 'safari_jeep',
                'terrain_capability' => 'off_road_4x4',
                'pricing_model' => 'per_day',
                'rate_per_day' => 24000.00,
                'rate_per_km' => null,
                'passenger_capacity' => 6,
                'latitude' => 6.2840,
                'longitude' => 81.3910,
            ],
            [
                'owner_name' => 'Sanath Weerakoon',
                'owner_email' => 'sanath.weerakoon@example.com',
                'vehicle_make_model' => 'Mahindra Bolero Maxi Camper 4x4',
                'registration_number' => 'SP NA-8890',
                'rental_type' => 'with_driver',
                'driver_name' => 'Kithsiri Silva',
                'contact_number' => '+94713334455',
                'whatsapp_number' => '+94713334455',
                'vehicle_type' => 'safari_jeep',
                'terrain_capability' => 'off_road_4x4',
                'pricing_model' => 'per_day',
                'rate_per_day' => 18000.00,
                'rate_per_km' => null,
                'passenger_capacity' => 6,
                'latitude' => 6.2825,
                'longitude' => 81.2915,
            ],
            [
                'owner_name' => 'Pradeep Wickramasinghe',
                'owner_email' => 'pradeep.wickramasinghe@example.com',
                'vehicle_make_model' => 'Mitsubishi Montero 4WD',
                'registration_number' => 'WP GA-3321',
                'rental_type' => 'self_drive',
                'driver_name' => null,
                'contact_number' => '+94774445566',
                'whatsapp_number' => '+94774445566',
                'vehicle_type' => 'suv_4x4',
                'terrain_capability' => 'off_road_4x4',
                'pricing_model' => 'both',
                'rate_per_day' => 32000.00,
                'rate_per_km' => 180.00,
                'passenger_capacity' => 5,
                'latitude' => 6.2900,
                'longitude' => 81.3200,
            ],

            // =========================================================================
            // 2. MEEMURE & KNUCKLES RANGE (Rugged Mountain 4x4)
            // =========================================================================
            [
                'owner_name' => 'Banda Tennekoon',
                'owner_email' => 'banda.tennekoon@example.com',
                'vehicle_make_model' => 'Toyota Hilux 4x4 Double Cab',
                'registration_number' => 'CP DA-1120',
                'rental_type' => 'with_driver',
                'driver_name' => 'Banda Tennekoon',
                'contact_number' => '+94715556677',
                'whatsapp_number' => '+94715556677',
                'vehicle_type' => 'suv_4x4',
                'terrain_capability' => 'off_road_4x4',
                'pricing_model' => 'per_day',
                'rate_per_day' => 22000.00,
                'rate_per_km' => null,
                'passenger_capacity' => 4,
                'latitude' => 7.4330,
                'longitude' => 80.8450,
            ],
            [
                'owner_name' => 'Niroshan Herath',
                'owner_email' => 'niroshan.herath@example.com',
                'vehicle_make_model' => 'Mitsubishi L200 4WD Utility Jeep',
                'registration_number' => 'CP GA-9801',
                'rental_type' => 'with_driver',
                'driver_name' => 'Niroshan Herath',
                'contact_number' => '+94776667788',
                'whatsapp_number' => '+94776667788',
                'vehicle_type' => 'suv_4x4',
                'terrain_capability' => 'off_road_4x4',
                'pricing_model' => 'per_day',
                'rate_per_day' => 20000.00,
                'rate_per_km' => null,
                'passenger_capacity' => 5,
                'latitude' => 7.3950,
                'longitude' => 80.7070,
            ],

            // =========================================================================
            // 3. MINNERIYA & HABARANA (Elephant Safari Specialists)
            // =========================================================================
            [
                'owner_name' => 'Asela Ekanayake',
                'owner_email' => 'asela.ekanayake@example.com',
                'vehicle_make_model' => 'Toyota Hilux Safari Open Top',
                'registration_number' => 'NC PB-6671',
                'rental_type' => 'with_driver',
                'driver_name' => 'Asela Ekanayake',
                'contact_number' => '+94778889900',
                'whatsapp_number' => '+94778889900',
                'vehicle_type' => 'safari_jeep',
                'terrain_capability' => 'off_road_4x4',
                'pricing_model' => 'per_day',
                'rate_per_day' => 17000.00,
                'rate_per_km' => null,
                'passenger_capacity' => 6,
                'latitude' => 8.0320,
                'longitude' => 80.7520,
            ],
            [
                'owner_name' => 'Sarath Kumara',
                'owner_email' => 'sarath.kumara@example.com',
                'vehicle_make_model' => 'Isuzu D-Max Safari Spec',
                'registration_number' => 'NC PA-5542',
                'rental_type' => 'with_driver',
                'driver_name' => 'Sarath Kumara',
                'contact_number' => '+94717778899',
                'whatsapp_number' => '+94717778899',
                'vehicle_type' => 'safari_jeep',
                'terrain_capability' => 'off_road_4x4',
                'pricing_model' => 'per_day',
                'rate_per_day' => 16500.00,
                'rate_per_km' => null,
                'passenger_capacity' => 6,
                'latitude' => 8.0350,
                'longitude' => 80.8260,
            ],

            // =========================================================================
            // 4. ELLA & CENTRAL HIGHLANDS (Tuk-Tuks, Scooters & Highland Passenger Vans)
            // =========================================================================
            [
                'owner_name' => 'Gayan Rathnayake',
                'owner_email' => 'gayan.rathnayake@example.com',
                'vehicle_make_model' => 'Bajaj RE 205cc Tuk-Tuk',
                'registration_number' => 'UP AAX-4412',
                'rental_type' => 'self_drive',
                'driver_name' => null,
                'contact_number' => '+94771122998',
                'whatsapp_number' => '+94771122998',
                'vehicle_type' => 'tuk_tuk',
                'terrain_capability' => 'standard_road',
                'pricing_model' => 'per_day',
                'rate_per_day' => 4500.00,
                'rate_per_km' => null,
                'passenger_capacity' => 3,
                'latitude' => 6.8715,
                'longitude' => 81.0470,
            ],
            [
                'owner_name' => 'Janaka Bandara',
                'owner_email' => 'janaka.bandara@example.com',
                'vehicle_make_model' => 'Honda Dio 110cc Scooter',
                'registration_number' => 'UP BBD-2109',
                'rental_type' => 'self_drive',
                'driver_name' => null,
                'contact_number' => '+94762233887',
                'whatsapp_number' => '+94762233887',
                'vehicle_type' => 'scooter',
                'terrain_capability' => 'standard_road',
                'pricing_model' => 'per_day',
                'rate_per_day' => 3000.00,
                'rate_per_km' => null,
                'passenger_capacity' => 2,
                'latitude' => 6.8728,
                'longitude' => 81.0482,
            ],
            [
                'owner_name' => 'Wasantha Dissanayake',
                'owner_email' => 'wasantha.dissanayake@example.com',
                'vehicle_make_model' => 'Toyota HiAce KDH Super GL Luxury Van',
                'registration_number' => 'WP PD-7819',
                'rental_type' => 'with_driver',
                'driver_name' => 'Dinesh Madushanka',
                'contact_number' => '+94714455990',
                'whatsapp_number' => '+94714455990',
                'vehicle_type' => 'passenger_van',
                'terrain_capability' => 'standard_road',
                'pricing_model' => 'both',
                'rate_per_day' => 26000.00,
                'rate_per_km' => 140.00,
                'passenger_capacity' => 9,
                'latitude' => 6.8670,
                'longitude' => 81.0510,
            ],
            [
                'owner_name' => 'Chinthaka Senaratne',
                'owner_email' => 'chinthaka.senaratne@example.com',
                'vehicle_make_model' => 'Toyota Axio Hybrid Sedan',
                'registration_number' => 'WP CAG-5510',
                'rental_type' => 'with_driver',
                'driver_name' => 'Chinthaka Senaratne',
                'contact_number' => '+94775566112',
                'whatsapp_number' => '+94775566112',
                'vehicle_type' => 'sedan_car',
                'terrain_capability' => 'standard_road',
                'pricing_model' => 'per_km',
                'rate_per_day' => null,
                'rate_per_km' => 120.00,
                'passenger_capacity' => 4,
                'latitude' => 6.9680,
                'longitude' => 80.7690,
            ],

            // =========================================================================
            // 5. SOUTH COAST (Mirissa, Weligama, Unawatuna, Galle Fort)
            // =========================================================================
            [
                'owner_name' => 'Tharaka Mendis',
                'owner_email' => 'tharaka.mendis@example.com',
                'vehicle_make_model' => 'Yamaha RayZR 125cc Scooter',
                'registration_number' => 'SP BCB-9981',
                'rental_type' => 'self_drive',
                'driver_name' => null,
                'contact_number' => '+94771231122',
                'whatsapp_number' => '+94771231122',
                'vehicle_type' => 'scooter',
                'terrain_capability' => 'standard_road',
                'pricing_model' => 'per_day',
                'rate_per_day' => 3200.00,
                'rate_per_km' => null,
                'passenger_capacity' => 2,
                'latitude' => 5.9460,
                'longitude' => 80.4560,
            ],
            [
                'owner_name' => 'Kasun Gamage',
                'owner_email' => 'kasun.gamage@example.com',
                'vehicle_make_model' => 'Bajaj Compact 4-Stroke Tuk-Tuk',
                'registration_number' => 'SP AAZ-7120',
                'rental_type' => 'self_drive',
                'driver_name' => null,
                'contact_number' => '+94762345566',
                'whatsapp_number' => '+94762345566',
                'vehicle_type' => 'tuk_tuk',
                'terrain_capability' => 'standard_road',
                'pricing_model' => 'per_day',
                'rate_per_day' => 4000.00,
                'rate_per_km' => null,
                'passenger_capacity' => 3,
                'latitude' => 5.9490,
                'longitude' => 80.4620,
            ],
            [
                'owner_name' => 'Chandana De Silva',
                'owner_email' => 'chandana.desilva@example.com',
                'vehicle_make_model' => 'Toyota Prius Hybrid Sedan',
                'registration_number' => 'WP CAD-4419',
                'rental_type' => 'with_driver',
                'driver_name' => 'Chandana De Silva',
                'contact_number' => '+94718899112',
                'whatsapp_number' => '+94718899112',
                'vehicle_type' => 'sedan_car',
                'terrain_capability' => 'standard_road',
                'pricing_model' => 'both',
                'rate_per_day' => 16000.00,
                'rate_per_km' => 110.00,
                'passenger_capacity' => 4,
                'latitude' => 6.0260,
                'longitude' => 80.2160,
            ],
            [
                'owner_name' => 'Mahesh Karunaratne',
                'owner_email' => 'mahesh.karunaratne@example.com',
                'vehicle_make_model' => 'Toyota Coaster Mini Bus (29-Seater)',
                'registration_number' => 'WP NA-7718',
                'rental_type' => 'with_driver',
                'driver_name' => 'Sunil Shantha',
                'contact_number' => '+94773344991',
                'whatsapp_number' => '+94773344991',
                'vehicle_type' => 'mini_bus',
                'terrain_capability' => 'standard_road',
                'pricing_model' => 'per_day',
                'rate_per_day' => 48000.00,
                'rate_per_km' => null,
                'passenger_capacity' => 28,
                'latitude' => 6.0140,
                'longitude' => 80.2450,
            ],

            // =========================================================================
            // 6. CULTURAL TRIANGLE (Sigiriya, Dambulla, Anuradhapura, Polonnaruwa)
            // =========================================================================
            [
                'owner_name' => 'Nalin Dambulla',
                'owner_email' => 'nalin.dambulla@example.com',
                'vehicle_make_model' => 'Bajaj Maxima Z Tuk-Tuk',
                'registration_number' => 'CP AAY-3301',
                'rental_type' => 'with_driver',
                'driver_name' => 'Nalin Dambulla',
                'contact_number' => '+94771122880',
                'whatsapp_number' => '+94771122880',
                'vehicle_type' => 'tuk_tuk',
                'terrain_capability' => 'standard_road',
                'pricing_model' => 'per_day',
                'rate_per_day' => 5000.00,
                'rate_per_km' => null,
                'passenger_capacity' => 3,
                'latitude' => 7.8570,
                'longitude' => 80.6490,
            ],
            [
                'owner_name' => 'Sujith Alahakoon',
                'owner_email' => 'sujith.alahakoon@example.com',
                'vehicle_make_model' => 'Toyota Premio 260 Luxury Sedan',
                'registration_number' => 'WP CAX-8809',
                'rental_type' => 'with_driver',
                'driver_name' => 'Sujith Alahakoon',
                'contact_number' => '+94719988112',
                'whatsapp_number' => '+94719988112',
                'vehicle_type' => 'sedan_car',
                'terrain_capability' => 'standard_road',
                'pricing_model' => 'both',
                'rate_per_day' => 17500.00,
                'rate_per_km' => 125.00,
                'passenger_capacity' => 4,
                'latitude' => 7.9550,
                'longitude' => 80.7510,
            ],
            [
                'owner_name' => 'Harsha Wanninayake',
                'owner_email' => 'harsha.wanninayake@example.com',
                'vehicle_make_model' => 'Toyota KDH Commuter High-Roof Van',
                'registration_number' => 'NC PE-9022',
                'rental_type' => 'with_driver',
                'driver_name' => 'Harsha Wanninayake',
                'contact_number' => '+94762233001',
                'whatsapp_number' => '+94762233001',
                'vehicle_type' => 'passenger_van',
                'terrain_capability' => 'standard_road',
                'pricing_model' => 'per_day',
                'rate_per_day' => 28000.00,
                'rate_per_km' => null,
                'passenger_capacity' => 14,
                'latitude' => 8.3120,
                'longitude' => 80.4040,
            ],

            // =========================================================================
            // 7. EAST COAST & SURF HUBS (Arugam Bay & Nilaveli Beach)
            // =========================================================================
            [
                'owner_name' => 'Rizwan Mohamed',
                'owner_email' => 'rizwan.mohamed@example.com',
                'vehicle_make_model' => 'TVS King Deluxe Tuk-Tuk (Surf Rack Fitted)',
                'registration_number' => 'EP AAW-1902',
                'rental_type' => 'self_drive',
                'driver_name' => null,
                'contact_number' => '+94773322884',
                'whatsapp_number' => '+94773322884',
                'vehicle_type' => 'tuk_tuk',
                'terrain_capability' => 'standard_road',
                'pricing_model' => 'per_day',
                'rate_per_day' => 4800.00,
                'rate_per_km' => null,
                'passenger_capacity' => 3,
                'latitude' => 6.8420,
                'longitude' => 81.8280,
            ],
            [
                'owner_name' => 'Firas Hameed',
                'owner_email' => 'firas.hameed@example.com',
                'vehicle_make_model' => 'Yamaha FZ-S 150cc Motorbike',
                'registration_number' => 'EP BCD-4421',
                'rental_type' => 'self_drive',
                'driver_name' => null,
                'contact_number' => '+94715566009',
                'whatsapp_number' => '+94715566009',
                'vehicle_type' => 'motorbike',
                'terrain_capability' => 'standard_road',
                'pricing_model' => 'per_day',
                'rate_per_day' => 3800.00,
                'rate_per_km' => null,
                'passenger_capacity' => 2,
                'latitude' => 6.8450,
                'longitude' => 81.8295,
            ],
            [
                'owner_name' => 'Selvakumar Thillai',
                'owner_email' => 'selvakumar.thillai@example.com',
                'vehicle_make_model' => 'Toyota HiAce GL Passenger Van',
                'registration_number' => 'EP PC-4412',
                'rental_type' => 'with_driver',
                'driver_name' => 'Selvakumar Thillai',
                'contact_number' => '+94778899334',
                'whatsapp_number' => '+94778899334',
                'vehicle_type' => 'passenger_van',
                'terrain_capability' => 'standard_road',
                'pricing_model' => 'both',
                'rate_per_day' => 25000.00,
                'rate_per_km' => 135.00,
                'passenger_capacity' => 10,
                'latitude' => 8.6850,
                'longitude' => 81.1840,
            ],

            // =========================================================================
            // 8. NORTHERN PROVINCE (Jaffna & Nallur)
            // =========================================================================
            [
                'owner_name' => 'Raveendran Nadarajah',
                'owner_email' => 'raveendran.nadarajah@example.com',
                'vehicle_make_model' => 'Bajaj RE 2-Stroke Classic Tuk-Tuk',
                'registration_number' => 'NP AAR-9901',
                'rental_type' => 'with_driver',
                'driver_name' => 'Raveendran Nadarajah',
                'contact_number' => '+94771199443',
                'whatsapp_number' => '+94771199443',
                'vehicle_type' => 'tuk_tuk',
                'terrain_capability' => 'standard_road',
                'pricing_model' => 'per_day',
                'rate_per_day' => 4500.00,
                'rate_per_km' => null,
                'passenger_capacity' => 3,
                'latitude' => 9.6730,
                'longitude' => 80.0280,
            ],
            [
                'owner_name' => 'Senthil Arumugam',
                'owner_email' => 'senthil.arumugam@example.com',
                'vehicle_make_model' => 'Toyota Corolla Fielder Wagon',
                'registration_number' => 'NP CAC-3390',
                'rental_type' => 'with_driver',
                'driver_name' => 'Senthil Arumugam',
                'contact_number' => '+94762233990',
                'whatsapp_number' => '+94762233990',
                'vehicle_type' => 'sedan_car',
                'terrain_capability' => 'standard_road',
                'pricing_model' => 'both',
                'rate_per_day' => 15000.00,
                'rate_per_km' => 115.00,
                'passenger_capacity' => 4,
                'latitude' => 9.6650,
                'longitude' => 80.0160,
            ],

            // =========================================================================
            // 9. COLOMBO COMMERCIAL CAPITAL & AIRPORT TRANSFERS
            // =========================================================================
            [
                'owner_name' => 'Nuwan Kulatunga',
                'owner_email' => 'nuwan.kulatunga@example.com',
                'vehicle_make_model' => 'Mercedes-Benz E-Class Luxury Sedan',
                'registration_number' => 'WP CBA-0012',
                'rental_type' => 'with_driver',
                'driver_name' => 'Nuwan Kulatunga',
                'contact_number' => '+94775550011',
                'whatsapp_number' => '+94775550011',
                'vehicle_type' => 'sedan_car',
                'terrain_capability' => 'standard_road',
                'pricing_model' => 'both',
                'rate_per_day' => 38000.00,
                'rate_per_km' => 220.00,
                'passenger_capacity' => 4,
                'latitude' => 6.9250,
                'longitude' => 79.8460,
            ],
            [
                'owner_name' => 'Rohan Samaraweera',
                'owner_email' => 'rohan.samaraweera@example.com',
                'vehicle_make_model' => 'Toyota KDH Grand Cabin Super Long',
                'registration_number' => 'WP PF-2291',
                'rental_type' => 'with_driver',
                'driver_name' => 'Priyantha Dias',
                'contact_number' => '+94718877221',
                'whatsapp_number' => '+94718877221',
                'vehicle_type' => 'passenger_van',
                'terrain_capability' => 'standard_road',
                'pricing_model' => 'both',
                'rate_per_day' => 30000.00,
                'rate_per_km' => 150.00,
                'passenger_capacity' => 12,
                'latitude' => 6.9180,
                'longitude' => 79.8510,
            ],
            [
                'owner_name' => 'Damith Gunawardana',
                'owner_email' => 'damith.gunawardana@example.com',
                'vehicle_make_model' => 'Mitsubishi Rosa Luxury Coach (33-Seater)',
                'registration_number' => 'WP NB-5512',
                'rental_type' => 'with_driver',
                'driver_name' => 'Damith Gunawardana',
                'contact_number' => '+94776644229',
                'whatsapp_number' => '+94776644229',
                'vehicle_type' => 'mini_bus',
                'terrain_capability' => 'standard_road',
                'pricing_model' => 'per_day',
                'rate_per_day' => 55000.00,
                'rate_per_km' => null,
                'passenger_capacity' => 32,
                'latitude' => 6.9300,
                'longitude' => 79.8500,
            ]
        ];

        foreach ($vehicles as $data) {
            // 1. Create or retrieve vendor user account
            $owner = User::updateOrCreate(
                ['email' => $data['owner_email']],
                [
                    'name' => $data['owner_name'],
                    'password' => Hash::make('password123'),
                    'role' => 'vehicle_owner',
                    'email_verified_at' => now(),
                ]
            );

            $lat = $data['latitude'];
            $lng = $data['longitude'];

            unset($data['owner_name'], $data['owner_email'], $data['latitude'], $data['longitude']);

            // 2. Insert Vehicle with PostGIS geography point
            $vehicle = new Vehicle($data);
            $vehicle->user_id = $owner->id;
            $vehicle->coordinates = DB::raw("ST_SetSRID(ST_MakePoint({$lng}, {$lat}), 4326)::geography");
            $vehicle->save();
        }
    }
}